### PR TITLE
feat: add truffle dashboard

### PR DESCRIPTION
**Pull request by alvaroserrrano**

### CODE REVIEW

**Comment by paulrberg** [comment]
Hi @alvaroserrrano, thanks for your PR. Could you explain your rationale for why it would be worth it to add the Truffle dashboard in this Solidity template?

The template is heavily based on Hardhat, which can't be used alongside Truffle - or rather it would be best to not use it alongside Truffle because things could break apart.

**Comment by alvaroserrrano** [comment]
Sure. After seeing this [announcement](https://trufflesuite.com/blog/introducing-truffle-dashboard/?utm_campaign=Truffle%20Release&utm_medium=email&_hsmi=204747071&utm_content=204747071&utm_source=hs_email), I saw that the dashboard is tool-agnostic and I thought that it might be helpful to be added to the template. The reason for that is that new developers will eventually get more interested about Solidity programming and, given that this template is one of the most complete, we could prevent human mistakes copy-pasting private keys, uploading to open source by mistake...

Let me know what you think after checking out the article, although I also understand your view and agree with your point of making it Hardhat-oriented

**Comment by SvenMeyer** [comment]
@alvaroserrrano There are likely enough truffle based templates out there.
So I would suggest truffle users go with one of them, and not bloating up a hardhat template.
Nobody wants 2 frameworks in one repo with the risk that things blow up. That would be time consuming for experts and not possible to handle for new developers.

**Comment by alvaroserrrano** [comment]
I can see your point. Perhaps it is better to keep that vision for this project. Feel free to close the PR 😉 , there is nothing wrong with that on my side. This template is already very complete, good work on that. I will try to come up with more constructive PRs 😄

**Pull request closed without merging**
