### PR TITLE
WIP: Hardhat migration

### PR DESCRIPTION
**Pull request by TomAFrench**
Changelog:

- [x] update all packages to their hardhat variant
- [x] use `hardhat-typechain` rather than custom task for typechain types
- [x] add `hardhat-spdx-license-identifier`
- [x] resupport solidity-coverage (subject to https://github.com/sc-forks/solidity-coverage/issues/541)

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Whoah, thanks for this dude!

**Comment by TomAFrench** [comment]
Looks like `solidity-coverage` support is here.

**Comment by PaulRBerg** [comment]
Yeah this is on my to-do list.

**Comment by PaulRBerg** [comment]
It looks like there is a mismatched dependency:

>  hardhat-typechain@0.3.3" has incorrect peer dependency "typechain@^3.0.0"

I'll fix it myself and push to your branch.

**Comment by PaulRBerg** [comment]
One thing that I really don't like is including `hardhat-spdx-license-identifier`. It's an opinionated tool that doesn't add much value - the Solidity compiler would warn the user about the missing SPDX identifiers anyways.

**Comment by TomAFrench** [comment]
> One thing that I really don't like is including hardhat-spdx-license-identifier. It's an opinionated tool that doesn't add much value - the Solidity compiler would warn the user about the missing SPDX identifiers anyways.

Fair enough. I find it useful but definitely see why others may have feel otherwise.

Agree on the `0 sources` messages though. May make a PR for that at some point

**Comment by PaulRBerg** [comment]
Yeah if they remove that message, happy to add it back.

**Pull request merged**
