### PR TITLE
Upgrade typechain target

### PR DESCRIPTION
**Pull request by zemse**
Upgrade typechain target to `v5.0.0` and update breaking changes in the tests.

### CODE REVIEW

**Comment by paulrberg** [comment]
There are some things that I approve of in this PR and others that I don't.

I agree that it would be nice to upgrade to the latest version of TypeChain. But I'd prefer not to renounce on `deployContract`, because that would likely break compatibility with other features from Waffle such as the [Mock contract](https://ethereum-waffle.readthedocs.io/en/latest/).

**Comment by paulrberg** [comment]
Additionally, it looks like upgrading TypeChain would break compatibility with `hardhat-typechain` as well:

```
warning " > hardhat-typechain@0.3.3" has incorrect peer dependency "typechain@^3.0.0"
```

**Comment by paulrberg** [comment]
Hey @zemse I am sorry, I accidentally force-pushed to your remote and deleted your last commits. I pushed your changes + the ones that I added on the [zemse-pr](https://github.com/paulrberg/solidity-template/tree/zemse-pr) branch.

Can you pull that and create a new PR? 

Also just so I understand why I couldn't push my commits to your clone of the repo, can you tell me if you [disallowed edits from contributors](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) when you created this PR?

**Comment by zemse** [comment]
> can you tell me if you disallowed edits by maintainers when you created this PR?

I didn't manually do that, but just noticed that the tick is disabled. I think this could be a default behaviour on GitHub if a PR is created from main/default branch while could be ticked in case of non-default branch.

> that would likely break compatibility with other features from Waffle such as the Mock contract.

Oh I was not aware of that, thanks for reverting the changes!

> Can you pull that and create a new PR?

On this..

**Comment by zemse** [comment]
> Additionally, it looks like upgrading TypeChain would break compatibility with hardhat-typechain as well:

Did upgrading hardhat-typechain remove this warning? BTW there was no interface change in the `typechain` package when it went from v3 to v4. It was just the prettier package (used internally) was upgrade to 2 major versions above. But yeah, it'd be preferrable to get rid of the warning if `hardhat-typechain@0.3.4` doesn't do that yet.

**Pull request closed without merging**
