### PR TITLE
all commits can be seen here at original repo https://github.com/ahme…

### PR DESCRIPTION
**Pull request by ahmedali8**
**Question: What changes this PR will occur?**
Answer: I have added the following features to the branch and created a javascript version of solidity-template but you can check the features and accept them or create a new branch for this javascript version so if someone wants to use javascript instead of typescript then one can use this new branch of javascript and maybe you can add these new features and convert them to typescript and add them to your main branch

- auto verification of contracts on etherscan/bscscan/polygonscan when you deploy a contract on these networks
- auto creation of .txt file of flattened version of contract and written in flattened folder automatically
- addition of new networks in hardhat.config.js file

**Question: Does this PR produces any breaking changes?**
Answer: maybe, because it is in javascript and added new plugins of hardhat

### CODE REVIEW

**Comment by paulrberg** [comment]
Hi @ahmedali8! Perhaps you meant to make this PR against your fork of this repository?

**Comment by paulrberg** [comment]
I will have to politely reject this PR.

Any major refactor or new feature should be discussed in advance with the core maintainers. And at any rate, PRs from external contributors should be small or medium in size; any major refactor should be split up in smaller PRs.

I would prefer to keep using TypeScript for the template. And I would prefer to [keep it simple](https://en.wikipedia.org/wiki/KISS_principle) instead of stuffing it with lots of contracts and features. And I would to keep using the configuration files you deleted in the PR (e.g. `.commitlintrc.js`, `.czrc`, etc.).

**Comment by paulrberg** [comment]
This is not to say that I don't appreciate your intent. I really do. But this repo is meant to be an *opinionated* template of mine.

You are very welcome to fork it and build a template that fits your needs best.

**Comment by SvenMeyer** [comment]
@ahmedali8 The first time I used the template I was a little bit time pressed and was struggling with TypeScript (and wished there would be a JavaScript version).
Now that I used the template for another project and (finally) took the time to get more into TypeScript (what I wanted to do anyway), I definitely think it is the right approach for any serious project.

@paulrberg I was (and still) struggling at the beginning with the `types` folder, containing  `augmentations.d.ts` and  `index.ts`
Atm, I just replace `Greeter` with my contract name, but if there would be a little bit of guidance, that would be great.

All over, the template is great and a big help for me, I am using it for all my projects now. Thanks a lot, Paul !

**Comment by ahmedali8** [comment]
> I will have to politely reject this PR.
> 
> In general in the open-source world, any major refactor or new feature should be discussed in advance with the core maintainers. And at any rate, PRs from external contributors should be small or medium in size; any major refactor should be split up in smaller PRs.
> 
> I would prefer to keep using TypeScript for the template. And I would prefer to [keep it simple](https://en.wikipedia.org/wiki/KISS_principle) instead of stuffing it with lots of contracts and features. And I would prefer to keep using the configuration files you deleted in the PR (e.g. `.commitlintrc.js`, `.czrc`, etc.).

Thank you for your kind response @paulrberg , I highly appreciate it. Could I re-fork your repo and rework on small feature additions without major refactoring thus creating small PRs (ofcourse now in typescript) ?

**Comment by paulrberg** [comment]
>  I was (and still) struggling at the beginning with the `types` folder, containing `augmentations.d.ts` and `index.ts`.

Yeah that was ugly. In the meantime I moved that logic in [test/types.ts](https://github.com/paulrberg/solidity-template/blob/13fa8b59a7f3cabd2f14bad2510d208834cc2495/test/types.ts). Hopefully this is better now.

> All over, the template is great and a big help for me, I am using it for all my projects now. 

Glad to hear, @SvenMeyer!

> Could I re-fork your repo and rework on small feature additions without major refactoring thus creating small PRs (ofcourse now in typescript) ?

Of course you can. But let's discuss what you want to change or add via [Telegram](https://t.me/paulrberg), in advance.

**Comment by ahmedali8** [comment]
> Of course you can. But let's discuss what you want to change or add via [Telegram](https://t.me/paulrberg), in advance.

Sure, I'll get in touch with you soon, Thanks!

**Pull request closed without merging**
