### PR TITLE
refactor: migrate to hardhat-chai-matchers and hardhat-toolbox

### PR DESCRIPTION
**Pull request by ahmedali8**

### CODE REVIEW

**Comment by ahmedali8** [comment]
hey @paulrberg, I accidentally closed #119 so I created a new PR following your suggestions but still wasn't able to apply that rebase thing. Please check it out and provide feedback thanks

**Comment by paulrberg** [comment]
> but still wasn't able to apply that rebase thing

Well you can't do a rebase after you did a merge. I shared that bit of feedback so that you know about rebasing in the future :)

The flow, in general, should be something like this:

```sh
git checkout main
git pull origin main
git checkout your-feature-branch
git rebase main
```

And then you resolve the git conflicts (if any) and run `git push -f origin your-feature-branch`.

**Comment by paulrberg** [comment]
Now this LGTM. Thanks for your contribution @ahmedali8!

**Comment by ahmedali8** [comment]
Thanks @paulrberg

**Pull request merged**
